
language: node_js

sudo: false

node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4.2"
  - "5.0"

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^3"

install:
  - npm install

script:
  - npm test